'use strict';
module.exports.getComponentInstance = require('./lib/getComponentInstance');
module.exports.getComponentName = require('./lib/getComponentName');
module.exports.getComponentVersion = require('./lib/getComponentVersion');
module.exports.getPageInstance = require('./lib/getPageInstance');
module.exports.getPageVersion = require('./lib/getPageVersion');
module.exports.getListInstance = require('./lib/getListInstance');
module.exports.isComponent = require('./lib/isComponent');
module.exports.isDefaultComponent = require('./lib/isDefaultComponent');
module.exports.isPage = require('./lib/isPage');
module.exports.isList = require('./lib/isList');
module.exports.isUser = require('./lib/isUser');
module.exports.replaceVersion = require('./lib/replaceVersion');
